name: Rebuild playground

on:
  schedule:
    - cron: '*/14 * * * *'
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sf -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
